import { Chat, Chats, ChatState } from "~/pages/khan-7/messenger/types/Chat";

export const initialChats: { [key: Chats | string]: Chat } = {
  [Chats.TeamPlayer]: {
    id: Chats.TeamPlayer,
    name: "پاتریک لنچونی",
    avatar: "/assets/avatars/patrick.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "سلام",
        sender: "other",
        type: "text",
        time: new Date(1755057140).getTime(),
      },
      {
        id: "2",
        text: "سلام",
        sender: "me",
        type: "text",
        time: new Date(1755057140).getTime(),
      },
      {
        id: "3",
        text: "سه ویژگی بازیکن تیمی ایده آل رو داری؟",
        sender: "other",
        type: "text",
        time: new Date(1755057140).getTime(),
        deletable: true,
      },
    ],
  },
  [Chats.RakhshChat]: {
    id: Chats.RakhshChat,
    name: "رخش",
    avatar: "/assets/avatars/rakhsh.jpg",
    unreadCount: 1,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "سلام",
        type: "text",
        sender: "other",
        time: new Date(12871310400).getTime(),
      },
    ],
  },
  [Chats.Barghman]: {
    id: Chats.Barghman,
    name: "برق من",
    avatar: "/assets/avatars/bargheman.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "لطفا قبل رفتن برق رو خاموش  کنید",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
      },
    ],
  },
  [Chats.Tajamolian]: {
    id: Chats.Tajamolian,
    name: "امین تجملیان",
    avatar: "/assets/avatars/amin.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [],
  },
  [Chats.Pisano]: {
    id: Chats.Pisano,
    name: "Bonanno Pisano",
    avatar: "/assets/avatars/pisano.jpg",
    unreadCount: 1,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "Ciao amico!",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
        ltr: true,
      },
      {
        id: "2",
        text: "La mia torre è storta...",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
        ltr: true,
      },
      {
        id: "3",
        text: "Puoi aiutarmi a raddrizzarla?",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
        ltr: true,
      },
    ],
    input: {
      placeholder: "پیام خود را بنویسید... (فقط یک کاراکتر)",
      maxLength: 1,
    },
  },
  [Chats.Bruce]: {
    id: Chats.Bruce,
    name: "بروس بنر",
    avatar: "/assets/avatars/bruce.png",
    unreadCount: 1,
    state: ChatState.ACTIVE,
    disablePointerEvents: true,
    messages: [
      {
        id: "1",
        text: "تنهایی می‌خوای با دیو بجنگی؟",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
      },
      {
        id: "2",
        text: "کافیه یه چیز عوض شه... اون وقت منم میتونم بیام کمکت",
        type: "text",
        sender: "other",
        time: new Date().getTime(),
      },
    ],
    input: {
      placeholder: "از موس استفاده کن!",
      disabled: true,
    },
  },
  [Chats.OtaghFekr]: {
    id: Chats.OtaghFekr,
    name: "اتاق فکر روز برنامه نویس",
    avatar: "/assets/avatars/brain.png",
    unreadCount: 0,
    sendFile: true,
    messages: [
      {
        id: "1",
        text: "بچه ها حجم این عکسه خیلی زیاده، سایت نیاد پایین",
        sender: "محمد",
        type: "text",
        time: new Date().getTime(),
      },
      {
        id: "2",
        text: "باید تست کنیم! ",
        sender: "me",
        type: "text",
        time: new Date().getTime(),
      },
    ],
    state: ChatState.NONE,
  },
  [Chats.Parking]: {
    id: Chats.Parking,
    name: "گروه پارکینگ",
    avatar: "/assets/profiles/parking.png",
    unreadCount: 0,
    messages: [
      {
        id: "1",
        text: "پارکینگ جا هست؟",
        sender: "me",
        type: "text",
        time: new Date().getTime(),
      },
      {
        id: "2",
        text: "یکی خالیه",
        sender: "کاربر 1",
        type: "text",
        time: new Date().getTime(),
      },
      {
        id: "3",
        text: "فقط یکی ؟ من تا یک دقیقه دیگه اونجام!",
        sender: "me",
        type: "text",
        time: new Date().getTime(),
      },
    ],
    state: ChatState.NONE,
  },
};
