import { Chat, Chats, ChatState } from "~/pages/khan-7/messenger/types/Chat";

export const initialChats: { [key: Chats | string]: Chat } = {
  [Chats.Olad]: {
    id: Chats.Olad,
    name: "اولاد",
    avatar: "/assets/avatars/olad.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "قرارمون که یادت نرفته؟",
        sender: "other",
        type: "text",
        time: 3000000000004,
      },
      {
        id: "2",
        text: "جای دیو سپید در ازای ..... پول",
        sender: "other",
        type: "text",
        time: 3000000000003,
      },
      {
        id: "3",
        text: "واقعا آدم دندون گردی هستی",
        sender: "me",
        type: "text",
        time: 3000000000002,
      },
      {
        id: "4",
        text: "باشه جور می کنم برات",
        sender: "me",
        type: "text",
        time: 3000000000001,
      },
    ],
    input: {
      placeholder: "پول جمع کن بعد بیا...",
      disabled: true,
    },
  },
  [Chats.TeamPlayer]: {
    id: Chats.TeamPlayer,
    name: "پاتریک لنچونی",
    avatar: "/assets/avatars/patrick.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "سلام",
        sender: "other",
        type: "text",
        time: 2000000000000 - 1000000000000,
      },
      {
        id: "2",
        text: "سلام",
        sender: "me",
        type: "text",
        time: 2000000000000 - 1000000000001,
      },
      {
        id: "3",
        text: "سه ویژگی بازیکن تیمی ایده آل رو داری؟",
        sender: "other",
        type: "text",
        time: 2000000000000 - 1000000000002,
        deletable: true,
      },
    ],
  },
  [Chats.Barghman]: {
    id: Chats.Barghman,
    name: "برق من",
    avatar: "/assets/avatars/bargheman.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "لطفا قبل رفتن برق رو خاموش  کنید",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000004,
      },
    ],
  },
  [Chats.Tajamolian]: {
    id: Chats.Tajamolian,
    name: "امین تجملیان",
    avatar: "/assets/avatars/amin.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [],
    input: {
      placeholder: "سر کاری...",
    },
  },
  [Chats.Bruce]: {
    id: Chats.Bruce,
    name: "بروس بنر",
    avatar: "/assets/avatars/bruce.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    disablePointerEvents: true,
    messages: [
      {
        id: "1",
        text: "تنهایی می‌خوای با دیو بجنگی؟",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000005,
      },
      {
        id: "2",
        text: "کافیه یه چیز عوض شه... اون وقت منم میتونم بیام کمکت",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000006,
      },
    ],
    input: {
      placeholder: "از موس استفاده کن!",
      disabled: true,
    },
  },
  [Chats.Pisano]: {
    id: Chats.Pisano,
    name: "Bonanno Pisano",
    avatar: "/assets/avatars/pisano.jpg",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "Ciao amico!",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000007,
        ltr: true,
      },
      {
        id: "2",
        text: "La mia torre è storta...",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000008,
        ltr: true,
      },
      {
        id: "3",
        text: "Puoi aiutarmi a raddrizzarla?",
        type: "text",
        sender: "other",
        time: 2000000000000 - 1000000000009,
        ltr: true,
      },
    ],
    input: {
      placeholder: "پیام خود را بنویسید... (فقط یک کاراکتر)",
      maxLength: 1,
    },
  },
  [Chats.OtaghFekr]: {
    id: Chats.OtaghFekr,
    name: "اتاق فکر روز برنامه نویس",
    avatar: "/assets/avatars/brain.png",
    unreadCount: 0,
    sendFile: true,
    messages: [
      {
        id: "1",
        text: "بچه ها حجم این عکسه خیلی زیاده، سایت نیاد پایین",
        sender: "محمد",
        type: "text",
        time: 2000000000000 - 1000000000010,
      },
      {
        id: "2",
        text: "باید تست کنیم! ",
        sender: "me",
        type: "text",
        time: 2000000000000 - 1000000000011,
      },
    ],
    state: ChatState.NONE,
  },
  [Chats.Parking]: {
    id: Chats.Parking,
    name: "گروه پارکینگ",
    avatar: "/assets/profiles/parking.png",
    unreadCount: 0,
    messages: [
      {
        id: "1",
        text: "پارکینگ جا هست؟",
        sender: "me",
        type: "text",
        time: 2000000000000 - 1000000000012,
      },
      {
        id: "2",
        text: "یکی خالیه",
        sender: "کاربر 1",
        type: "text",
        time: 2000000000000 - 1000000000013,
      },
      {
        id: "3",
        text: "فقط یکی ؟ من تا یک دقیقه دیگه اونجام!",
        sender: "me",
        type: "text",
        time: 2000000000000 - 1000000000014,
      },
    ],
    state: ChatState.NONE,
  },

  [Chats.RakhshChat]: {
    id: Chats.RakhshChat,
    name: "رخش",
    avatar: "/assets/avatars/rakhsh.jpg",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "سلام",
        type: "text",
        sender: "other",
        time: 100000000000,
      },
    ],
    input: {
      placeholder: "سر کاری...",
    },
  },
  [Chats.Noskhe]: {
    id: Chats.Noskhe,
    name: "نسخه پزشکی",
    avatar: "/assets/avatars/noskhe.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [],
    input: {
      placeholder: "از من بپرس...",
    },
  },
  [Chats.Golzar]: {
    id: Chats.Golzar,
    name: "گلزار",
    avatar: "/assets/avatars/golzar.png",
    unreadCount: 0,
    state: ChatState.ACTIVE,
    messages: [
      {
        id: "1",
        text: "سلام داش گلم",
        type: "text",
        sender: "other",
        time: 1000,
      },
      {
        id: "1",
        text: "ببین چه ترکی خوندم",
        type: "text",
        sender: "other",
        time: 1005,
      },
      {
        id: "1",
        text: "ببین چه ترکی خوندم",
        type: "audio",
        sender: "other",
        time: 1005,
        audio: "https://dl.musicdel.ir/tag/music/1403/07/13/Mohammadreza%20Golzar%20-%20Kharab%20Kardi%20(128).mp3",
      },
    ],
    input: {
      placeholder: "از من بپرس...",
    },
  },
};

